version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "CL-BuildPackaging"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    labels:
      - "CL-BuildPackaging"
  
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "CL-BuildPackaging"
    target-branch: "master"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "CL-BuildPackaging"
    target-branch: "master"
