name: 🐛 Bug Report
description: Create a report to help us improve
title: "[BUG]: "
labels:
  - "Type-Bug"
  - "Needs-Triage"
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please search existing issues before creating a new one to avoid duplicates.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm these before submitting
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I am using the latest version of PowerShell
          required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g. Windows 11, Ubuntu 22.04, macOS 13]
        - PowerShell Version: [e.g. 7.4.0]
        - .NET Version: [e.g. 8.0.1]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information, screenshots, or logs
      placeholder: Add any other context about the problem here...
